### ISSUE TITLE
No connection when NLA is enabled

### ISSUE THREAD

**Issue by Zjemm** [szatanszmatan/myrdp#1]
Hi,

I found that when the windows client has NLA enabled (default in windows 10) i cannot connect from myrdp. I first have to disable it on the windows client and then i'm able to connect

NLA support is needed :)

I really like this peace of software. Keep up the good work

Some extra idea's:
- connection grouping - create groups in the left menu and add the connections to groups
- connection settings - add the domain field as a seperate field for login.
- Display settings - give posibility to edit the diplay settings (colour depth/ resolution/ etc)
- file sharing -  add the support to drag and drop files to the remote machine, of via some shared folder like remmina does.

What would really make it cool:
- add support for SSH connections too (the same way as with RDP) like MRemoteNG did

Kind regards
Zjemm

**Comment by szatanszmatan** [comment]
Hello Zjemm,

Thank you for creating issue ;) Some of extra ideas can be already done in conf/config.yaml. At this time, there is no any manual to do this file, because I'm planning to make possibility of changing configuration in GUI.

As default, in config.yaml, xfreerdp client is used and if you wish to enable NLA support, you should change in xfreerdp -> args "-sec-nla" to "+sec-nla".

To add some share, to your connections you can add to args for example: "/drive:home,/home".

To change colour depth you can add arg like this "/bpp:16".

All possible arguments to Freerdp you can find here https://github.com/FreeRDP/FreeRDP/wiki/CommandLineInterface, but you propably never should use /w,/h,/u,/v ;)

All changes in config.yaml are global, and at this time after some changes, application restart is required.

I agree with connection grouping idea, and I'm planning to add support for this in future.

Separate domain field is also good idea. I'm adding this position to my TODO list ;)

Support for SSH at this time is not planned, because my favourite way to use SSH is using terminator terminal :) But in the distant future who knows ;)


Best regards
mj

**Comment by Zjemm** [comment]
Hi Mj,

Thanks for your explenation. the settings do work nicely

Do you have any idea when a new version wil come out? 

As for the SSH idea, well if you do manage to get it in, this will be a master tool i can guarante :)

One thing i noticed is that the db file is created in the path where the application is started from.
i started it at first from the myrdp folder, set up some connections, and later i started it from another location in attempt to make some sort of application launcher in gnome 3 and all the connections were gone. later i discovered it created a new empty file :P

**Comment by szatanszmatan** [comment]
Ok, I have committed changes to detect relative path for db file not by working directory ;) Thank you for report ;)

I don't have any idea when new version will come out, but I always tries to commit each improvement/bug fix only if is working ;) At this time git repository should be always stable.

**Comment by Zjemm** [comment]
Thnx,

I'll follow your project.

**Comment by Zjemm** [comment]
Hi, how's is the project going? still working on it?

**Comment by szatanszmatan** [comment]
Hi, at this time I'm working on some other home project, and I don't have a lot of time to work on myrdp. But in unspecified future I will back to do something in myrdp.

For changing logging settings I have created other issue #2 ;)

**Comment by Tahvok** [comment]
@szatanszmatan I tried it long time ago, and wanted to open issue now, but I see that's it been done already.
Not specifying -sec-nla or +sec-nla at all, will make xfreerdp to automatically detect the security protocol.
I've been using it like this for almost an year (by updating the conf/config.yaml file), and it's been working completely fine for me, for both nla only and non nla machines.
Can you check on your side, and consider removing in the master as well?

**Comment by szatanszmatan** [comment]
I have checked on windows server 2008r2/2012r2/2016 (with enabled/disabled NLA in Remote Desktop settings), windows 10 and XP. Looks that xfreerdp (version 2.0.0-dev git 90877f5ac) works fine without option +/- sec-nla :) Change in config.yaml commited, @Tahvok thank you for info ;) Issue closed.
